pg = pg or {}
pg.ship_data_create_material = {
	{
		use_gold = 1500,
		name = "Special Ship",
		exchange_request = 0,
		type = 1,
		ship_icon = "1",
		exchange_available_times = 0,
		build_anim = "building",
		build_voice = "",
		use_item = 20001,
		number_1 = 2,
		id = 1,
		icon = "build_1",
		exchange_ship_id = 0,
		rate_tip = {
			"<color=#ffde38>Super Rare</color>：7%",
			"<color=#d797ff>Elite</color>：12%",
			"<color=#3dc6ff>Rare</color>：51%",
			"Common：30%"
		}
	},
	{
		use_gold = 600,
		name = "Light Ship",
		exchange_request = 0,
		type = 1,
		ship_icon = "2",
		exchange_available_times = 0,
		build_anim = "building",
		build_voice = "",
		use_item = 20001,
		number_1 = 1,
		id = 2,
		icon = "build_2",
		exchange_ship_id = 0,
		rate_tip = {
			"<color=#ffde38>Super Rare</color>：7%",
			"<color=#d797ff>Elite</color>：12%",
			"<color=#3dc6ff>Rare</color>：26%",
			"Common：55%"
		}
	},
	{
		use_gold = 1500,
		name = "Heavy Ship",
		exchange_request = 0,
		type = 1,
		ship_icon = "3",
		exchange_available_times = 0,
		build_anim = "building",
		build_voice = "",
		use_item = 20001,
		number_1 = 2,
		id = 3,
		icon = "build_3",
		exchange_ship_id = 0,
		rate_tip = {
			"<color=#ffde38>Super Rare</color>：7%",
			"<color=#d797ff>Elite</color>：12%",
			"<color=#3dc6ff>Rare</color>：51%",
			"Common：30%"
		}
	},
	{
		use_gold = 1500,
		name = "Limited Build",
		exchange_request = 0,
		type = 2,
		ship_icon = "1",
		exchange_available_times = 0,
		build_anim = "building",
		build_voice = "",
		use_item = 20001,
		number_1 = 2,
		id = 4,
		icon = "build_4",
		exchange_ship_id = 0,
		rate_tip = {
			"<color=#ffde38>Super Rare</color>: 7%",
			"<color=#d797ff>Elite</color>: 12%",
			"<color=#3dc6ff>Rare</color>: 51%",
			"Common: 30%",
			"<color=#ffde38>{namecode:179}</color>: 2.0%(<color=#92fc63>up!</color>)",
			"<color=#ffde38>{namecode:175}</color>: 2.0%(<color=#92fc63>up!</color>)",
			"<color=#ffde38>{namecode:203}</color>: 2.0%(<color=#92fc63>up!</color>)",
			"<color=#ffde38>{namecode:50}</color>: 0.5%",
			"<color=#d797ff>{namecode:180}</color>: 2.5%(<color=#92fc63>up!</color>)",
			"<color=#d797ff>{namecode:3}</color>: 2.5%(<color=#92fc63>up!</color>)",
			"<color=#d797ff>{namecode:181}</color>: 0.7%"
		}
	},
	{
		use_gold = 1500,
		name = "Limited Build",
		exchange_request = 0,
		type = 2,
		ship_icon = "1",
		exchange_available_times = 0,
		build_anim = "building",
		build_voice = "",
		use_item = 20001,
		number_1 = 2,
		id = 5,
		icon = "build_5",
		exchange_ship_id = 0,
		rate_tip = {
			"<color=#ffde38>Super Rare</color>：7%",
			"<color=#d797ff>Elite</color>：12%",
			"<color=#3dc6ff>Rare</color>：51%",
			"Common：30%"
		}
	},
	{
		use_gold = 1500,
		name = "Wishing Well - Special",
		exchange_request = 0,
		type = 2,
		ship_icon = "1",
		exchange_available_times = 0,
		build_anim = "building",
		build_voice = "",
		use_item = 20001,
		number_1 = 2,
		id = 6,
		icon = "build_6",
		exchange_ship_id = 0,
		rate_tip = {
			"<color=#ffde38>Super Rare</color>：7%",
			"<color=#d797ff>Elite</color>：12%",
			"<color=#3dc6ff>Rare</color>：51%",
			"Common：30%"
		}
	},
	{
		use_gold = 600,
		name = "Wishing Well – Light",
		exchange_request = 0,
		type = 2,
		ship_icon = "2",
		exchange_available_times = 0,
		build_anim = "building",
		build_voice = "",
		use_item = 20001,
		number_1 = 1,
		id = 7,
		icon = "build_7",
		exchange_ship_id = 0,
		rate_tip = {
			"<color=#ffde38>Super Rare</color>：7%",
			"<color=#d797ff>Elite</color>：12%",
			"<color=#3dc6ff>Rare</color>：26%",
			"Common：55%"
		}
	},
	{
		use_gold = 1500,
		name = "Wishing Well - Heavy",
		exchange_request = 0,
		type = 2,
		ship_icon = "3",
		exchange_available_times = 0,
		build_anim = "building",
		build_voice = "",
		use_item = 20001,
		number_1 = 2,
		id = 8,
		icon = "build_8",
		exchange_ship_id = 0,
		rate_tip = {
			"<color=#ffde38>Super Rare</color>：7%",
			"<color=#d797ff>Elite</color>：12%",
			"<color=#3dc6ff>Rare</color>：51%",
			"Common：30%"
		}
	},
	{
		use_gold = 600,
		name = "Limited Build – Light",
		exchange_request = 0,
		type = 2,
		ship_icon = "2",
		exchange_available_times = 0,
		build_anim = "building",
		build_voice = "",
		use_item = 20001,
		number_1 = 1,
		id = 9,
		icon = "build_4",
		exchange_ship_id = 0,
		rate_tip = {
			"<color=#ffde38>Super Rare</color>：7%",
			"<color=#d797ff>Elite</color>：12%",
			"<color=#3dc6ff>Rare</color>：26%",
			"Common：55%",
			"<color=#d797ff>Tartu</color>：1.4%(<color=#92fc63>up!</color>)"
		}
	},
	{
		use_gold = 1500,
		name = "Limited Build",
		exchange_request = 200,
		type = 2,
		ship_icon = "1",
		exchange_available_times = 4,
		build_anim = "building",
		build_voice = "",
		use_item = 20001,
		number_1 = 2,
		id = 10,
		icon = "build_4",
		exchange_ship_id = 105171,
		rate_tip = {
			"<color=#ff5e39>Ultra Rare</color>：1.2%",
			"<color=#ffde38>Super Rare</color>：7%",
			"<color=#d797ff>Elite</color>：12%",
			"<color=#3dc6ff>Rare</color>：51%",
			"Common：28.8%",
			"<color=#ff5e39>New Jersey</color>：1.2%(<color=#92fc63>up!</color>)",
			"<color=#ffde38>San Francisco</color>：2.0%(<color=#92fc63>up!</color>)",
			"<color=#ffde38>Archerfish</color>：2.0%(<color=#92fc63>up!</color>)",
			"<color=#ffde38>Ticonderoga</color>：0.5%",
			"<color=#d797ff>Boise</color>：2.5%(<color=#92fc63>up!</color>)"
		}
	},
	all = {
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10
	}
}
