pg = pg or {}
pg.world_item_data_template = {
	[100] = {
		rarity = 2,
		display = "Can be exchanged for items in the Operation Siren store. Any unspent coins will be lost when operation progress resets.",
		sort_priority = 4,
		name = "Operation Supply Coins",
		expired_date = "",
		item_transform_resource_num = 1,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 100,
		id = 100,
		icon = "Props/Wdashijiehuobi",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			201,
			3,
			4,
			5,
			6,
			7
		}
	},
	[101] = {
		rarity = 3,
		display = "Can be exchanged for special items in the Operation Siren store. Any unspent tokens will be lost when operation progress resets.",
		sort_priority = 4,
		name = "Special Item Tokens",
		expired_date = "",
		item_transform_resource_num = 1,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 1,
		id = 101,
		icon = "Props/Wdashijiezhaungbeibi",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			201,
			3,
			7,
			8,
			9,
			10,
			11
		}
	},
	[102] = {
		rarity = 3,
		display = "A data storage device that logs information of zones where Sirens have appeared. You can clear out areas of the Operation Siren map without having to sortie again, and collect the associated rewards (bonus displayed on the Overview screen) as well. ",
		sort_priority = 4,
		name = "Operation Siren Data Logger",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_world_clean",
		open_box = "",
		item_transform_num = 0,
		id = 102,
		icon = "Props/xinxizhongduan4",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			101
		}
	},
	[110] = {
		rarity = 2,
		display = "A device that stores energy needed to operate Siren-made structures and equipment. Its failsafe construction ensures it will not explode.",
		sort_priority = 4,
		name = "Energy Storage Device",
		expired_date = "",
		item_transform_resource_num = 5,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 1,
		id = 110,
		icon = "Props/jingtidianchi",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			201,
			4,
			7
		}
	},
	[201] = {
		rarity = 2,
		display = "Can be used to restore the HP of 1 ship in your current fleet by 1,000.",
		sort_priority = 5,
		name = "Emergency Repair Pack",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_world_healing_value",
		open_box = "",
		item_transform_num = 0,
		id = 201,
		icon = "Props/Wshengminghuifu1",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			1,
			1000
		},
		item_origin = {
			100,
			201,
			4,
			7
		}
	},
	[202] = {
		rarity = 2,
		display = "Can be used to restore the HP of 1 ship in your current fleet by 3,000.",
		sort_priority = 5,
		name = "Complete Repair Pack",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_world_healing_value",
		open_box = "",
		item_transform_num = 0,
		id = 202,
		icon = "Props/Wshengminghuifu2",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			1,
			3000
		},
		item_origin = {
			100,
			201,
			4
		}
	},
	[203] = {
		rarity = 2,
		display = "Can be used to restore the HP of up to 3 ships in your current fleet by 500.",
		sort_priority = 5,
		name = "Triple Emergency Repair Pack",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_world_healing_value",
		open_box = "",
		item_transform_num = 0,
		id = 203,
		icon = "Props/Wshengminghuifu3",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			3,
			500
		},
		item_origin = {
			100,
			201,
			4,
			7
		}
	},
	[204] = {
		rarity = 2,
		display = "Can be used to restore the HP of up to 3 ships in your current fleet by 1,500.",
		sort_priority = 5,
		name = "Triple Complete Repair Pack",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_world_healing_value",
		open_box = "",
		item_transform_num = 0,
		id = 204,
		icon = "Props/Wshengminghuifu4",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			3,
			1500
		},
		item_origin = {
			100,
			201,
			4
		}
	},
	[205] = {
		rarity = 3,
		display = "Can be used to restore the HP of all ships in your current fleet by 30%.",
		sort_priority = 5,
		name = "Full Emergency Repair Pack",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_world_healing",
		open_box = "",
		item_transform_num = 0,
		id = 205,
		icon = "Props/Wshengminghuifu5",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			6,
			3000
		},
		item_origin = {
			100,
			201,
			4,
			7
		}
	},
	[206] = {
		rarity = 3,
		display = "Can be used to restore the HP of all ships in your current fleet by 100%.",
		sort_priority = 5,
		name = "Full Complete Repair Pack",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_world_healing",
		open_box = "",
		item_transform_num = 0,
		id = 206,
		icon = "Props/Wshengminghuifu6",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			6,
			10000
		},
		item_origin = {
			100,
			201,
			4,
			10
		}
	},
	[251] = {
		rarity = 2,
		display = "Can be used to restore 20 Action Points.",
		sort_priority = 6,
		name = "Action Point Refill (S)",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_world_recoverAP",
		open_box = "",
		item_transform_num = 0,
		id = 251,
		icon = "Props/Wxingdonglihuifu1",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			20
		},
		item_origin = {
			100,
			201,
			3
		}
	},
	[252] = {
		rarity = 3,
		display = "Can be used to restore 50 Action Points.",
		sort_priority = 6,
		name = "Action Point Refill (M)",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_world_recoverAP",
		open_box = "",
		item_transform_num = 0,
		id = 252,
		icon = "Props/Wxingdonglihuifu2",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			50
		},
		item_origin = {
			100,
			201,
			3
		}
	},
	[253] = {
		rarity = 4,
		display = "Can be used to restore 100 Action Points.",
		sort_priority = 6,
		name = "Action Point Refill (L)",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_world_recoverAP",
		open_box = "",
		item_transform_num = 0,
		id = 253,
		icon = "Props/Wxingdonglihuifu3",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			100
		},
		item_origin = {
			100,
			201
		}
	},
	[301] = {
		rarity = 2,
		display = "A decent sample of a Siren enhancement module. Use it to gain 5 points in the Offensive Adaptability stat.",
		sort_priority = 7,
		name = "Tuning Sample - Offense",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_worldSLGbuff",
		open_box = "",
		item_transform_num = 0,
		id = 301,
		icon = "Props/Wyangben1",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			401,
			5
		},
		item_origin = {
			100
		}
	},
	[302] = {
		rarity = 2,
		display = "A decent sample of a Siren enhancement module. Use it to gain 5 points in the Survivability Adaptability stat.",
		sort_priority = 7,
		name = "Tuning Sample - Survivability",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_worldSLGbuff",
		open_box = "",
		item_transform_num = 0,
		id = 302,
		icon = "Props/Wyangben3",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			402,
			5
		},
		item_origin = {
			100
		}
	},
	[303] = {
		rarity = 2,
		display = "A decent sample of a Siren enhancement module. Use it to gain 5 points in the Combat Adaptability stat.",
		sort_priority = 7,
		name = "Tuning Sample - Tactics",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_worldSLGbuff",
		open_box = "",
		item_transform_num = 0,
		id = 303,
		icon = "Props/Wyangben5",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			403,
			5
		},
		item_origin = {
			100
		}
	},
	[304] = {
		rarity = 3,
		display = "A quality sample of a Siren enhancement module. Use it to gain 10 points in the Offensive Adaptability stat.",
		sort_priority = 7,
		name = "Quality Tuning Sample - Offense",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_worldSLGbuff",
		open_box = "",
		item_transform_num = 0,
		id = 304,
		icon = "Props/Wyangben2",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			401,
			10
		},
		item_origin = {
			100
		}
	},
	[305] = {
		rarity = 3,
		display = "A quality sample of a Siren enhancement module. Use it to gain 10 points in the Survivability Adaptability stat.",
		sort_priority = 7,
		name = "Quality Tuning Sample - Survivability",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_worldSLGbuff",
		open_box = "",
		item_transform_num = 0,
		id = 305,
		icon = "Props/Wyangben4",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			402,
			10
		},
		item_origin = {
			100
		}
	},
	[306] = {
		rarity = 3,
		display = "A quality sample of a Siren enhancement module. Use it to gain 10 points in the Combat Adaptability stat.",
		sort_priority = 7,
		name = "Quality Tuning Sample - Tactics",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_worldSLGbuff",
		open_box = "",
		item_transform_num = 0,
		id = 306,
		icon = "Props/Wyangben6",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {
			403,
			10
		},
		item_origin = {
			100
		}
	},
	[2002] = {
		rarity = 2,
		display = "A peculiar device that has recorded coordinates from a zone with minor levels of Siren encroachment, with a Corrosion level of 2.",
		sort_priority = 1,
		name = "R2 Coordinate Logger",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 1,
		usage_arg = "1030001",
		id = 2002,
		icon = "Props/Wluopanputong2",
		log_text = "",
		item_transform_resource = 3002,
		item_origin = {
			100,
			7
		}
	},
	[2003] = {
		rarity = 3,
		display = "A peculiar device that has recorded coordinates from a zone with minor levels of Siren encroachment, with a Corrosion level of 3.",
		sort_priority = 1,
		name = "R3 Coordinate Logger",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 1,
		usage_arg = "1030002",
		id = 2003,
		icon = "Props/Wluopanputong3",
		log_text = "",
		item_transform_resource = 3002,
		item_origin = {
			100,
			7
		}
	},
	[2004] = {
		rarity = 3,
		display = "A peculiar device that has recorded coordinates from a zone with moderate levels of Siren encroachment, with a Corrosion level of 4.",
		sort_priority = 1,
		name = "R4 Coordinate Logger",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 1,
		usage_arg = "1030003",
		id = 2004,
		icon = "Props/Wluopanputong4",
		log_text = "",
		item_transform_resource = 3002,
		item_origin = {
			100,
			7
		}
	},
	[2005] = {
		rarity = 4,
		display = "A peculiar device that has recorded coordinates from a zone with moderate levels of Siren encroachment, with a Corrosion level of 5.",
		sort_priority = 1,
		name = "R5 Coordinate Logger",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 1,
		usage_arg = "1030004",
		id = 2005,
		icon = "Props/Wluopanputong5",
		log_text = "",
		item_transform_resource = 3002,
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[2006] = {
		rarity = 4,
		display = "A peculiar device that has recorded coordinates from a zone with significant levels of Siren encroachment, with a Corrosion level of 6.",
		sort_priority = 1,
		name = "R6 Coordinate Logger",
		expired_date = "",
		item_transform_resource_num = 160,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 1,
		usage_arg = "1030005",
		id = 2006,
		icon = "Props/Wluopanputong6",
		log_text = "",
		item_transform_resource = 3002,
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[2014] = {
		rarity = 4,
		display = "A peculiar device that has recorded coordinates from a zone with a moderately dangerous Siren present, with a Corrosion level of 4.",
		sort_priority = 1,
		name = "R4 Siren Coordinate Logger",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 1,
		usage_arg = "1030006",
		id = 2014,
		icon = "Props/Wsairenluopanputong4",
		log_text = "",
		item_transform_resource = 3002,
		item_origin = {
			100,
			101,
			7
		}
	},
	[2015] = {
		rarity = 4,
		display = "A peculiar device that has recorded coordinates from a zone with a moderately dangerous Siren present, with a Corrosion level of 5.",
		sort_priority = 1,
		name = "R5 Siren Coordinate Logger",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 1,
		usage_arg = "1030007",
		id = 2015,
		icon = "Props/Wsairenluopanputong5",
		log_text = "",
		item_transform_resource = 3002,
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[2016] = {
		rarity = 5,
		display = "A peculiar device that has recorded coordinates from a zone with a highly dangerous Siren present, with a Corrosion level of 6.",
		sort_priority = 1,
		name = "R6 Siren Coordinate Logger",
		expired_date = "",
		item_transform_resource_num = 800,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 1,
		usage_arg = "1030008",
		id = 2016,
		icon = "Props/Wsairenluopanputong6",
		log_text = "",
		item_transform_resource = 3002,
		item_origin = {
			100,
			201,
			7
		}
	},
	[2101] = {
		rarity = 2,
		display = "Contains a random Rare building material.",
		sort_priority = 2,
		name = "T1 Development Materials Container",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 0,
		usage_arg = "1030009",
		id = 2101,
		icon = "Props/Wsucaixiang3",
		log_text = "",
		item_transform_resource = 0,
		item_origin = {
			100
		}
	},
	[2102] = {
		rarity = 3,
		display = "Contains a random Elite building material.",
		sort_priority = 2,
		name = "T2 Development Materials Container",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 0,
		usage_arg = "1030010",
		id = 2102,
		icon = "Props/Wsucaixiang2",
		log_text = "",
		item_transform_resource = 0,
		item_origin = {
			100
		}
	},
	[2103] = {
		rarity = 4,
		display = "Contains a random Super Rare building material.",
		sort_priority = 2,
		name = "T3 Development Materials Container",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 0,
		usage_arg = "1030011",
		id = 2103,
		icon = "Props/Wsucaixiang1",
		log_text = "",
		item_transform_resource = 0,
		item_origin = {
			100
		}
	},
	[2111] = {
		rarity = 3,
		display = "Contains a random Super Rare weapon design. Used in the Gear Lab.",
		sort_priority = 2,
		name = "SR Weapon Design Plans",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 0,
		usage_arg = "1030012",
		id = 2111,
		icon = "Props/18125",
		log_text = "",
		item_transform_resource = 0,
		item_origin = {
			100
		}
	},
	[2112] = {
		rarity = 4,
		display = "A field performance report on an experimental piece of ordnance. Used in the Gear Lab.",
		sort_priority = 2,
		name = "T2 Ordnance Testing Report",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 0,
		usage_arg = "1030013",
		id = 2112,
		icon = "Props/18126",
		log_text = "",
		item_transform_resource = 0,
		item_origin = {
			100
		}
	},
	[2113] = {
		rarity = 4,
		display = "Contains a random Super Rare gear part.",
		sort_priority = 2,
		name = "T4 Random Gear Part",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 0,
		usage_arg = "1030014",
		id = 2113,
		icon = "Props/Wsuijibujian",
		log_text = "",
		item_transform_resource = 0,
		item_origin = {
			100
		}
	},
	[2114] = {
		rarity = 4,
		display = "Upgrade material used to further enhance gear of Super Rare rarity or below.",
		sort_priority = 2,
		name = "Prototype Gear Upgrade Part",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 0,
		usage_arg = "1030015",
		id = 2114,
		icon = "Props/17990",
		log_text = "",
		item_transform_resource = 0,
		item_origin = {
			100
		}
	},
	[2115] = {
		rarity = 5,
		display = "Upgrade material used to further enhance gear of UR rarity or below.",
		sort_priority = 2,
		name = "Specialized Gear Upgrade Part",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 0,
		usage_arg = "1030016",
		id = 2115,
		icon = "Props/17991",
		log_text = "",
		item_transform_resource = 0,
		item_origin = {
			100
		}
	},
	[2116] = {
		rarity = 4,
		display = "Rare equipment used to improve the firepower capabilities of Ashes ships during Rigging Fortification.",
		sort_priority = 2,
		name = "Crystallized Heat-Resistant Steel",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 0,
		usage_arg = "1030017",
		id = 2116,
		icon = "Props/21101",
		log_text = "",
		item_transform_resource = 0,
		item_origin = {}
	},
	[2117] = {
		rarity = 4,
		display = "Rare equipment used to improve the aviation capabilities of Ashes ships during Rigging Fortification.",
		sort_priority = 2,
		name = "Nanoceramic Alloy",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 0,
		usage_arg = "1030018",
		id = 2117,
		icon = "Props/21111",
		log_text = "",
		item_transform_resource = 0,
		item_origin = {}
	},
	[2118] = {
		rarity = 4,
		display = "Rare equipment used to improve the reloading capabilities of Ashes ships during Rigging Fortification.",
		sort_priority = 2,
		name = "Neuroplastic Prosthetic Arm",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 0,
		usage_arg = "1030019",
		id = 2118,
		icon = "Props/21121",
		log_text = "",
		item_transform_resource = 0,
		item_origin = {}
	},
	[2119] = {
		rarity = 4,
		display = "Rare equipment used to improve the torpedo capabilities of Ashes ships during Rigging Fortification.",
		sort_priority = 2,
		name = "Supercavitation Generator",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 0,
		usage_arg = "1030020",
		id = 2119,
		icon = "Props/21131",
		log_text = "",
		item_transform_resource = 0,
		item_origin = {}
	},
	[2120] = {
		rarity = 4,
		display = "Blueprints for the development of a UR-rarity torpedo. Used in the Gear Lab.",
		sort_priority = 2,
		name = "UR Torpedo Design Plans",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 1,
		usage = "usage_drop_appointed",
		open_box = "",
		item_transform_num = 1,
		id = 2120,
		icon = "Props/Wshejitujin",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			{
				2,
				18117,
				1
			},
			{
				2,
				18119,
				1
			},
			{
				2,
				18121,
				1
			},
			{
				2,
				18123,
				1
			}
		},
		item_origin = {}
	},
	[2121] = {
		rarity = 5,
		display = "Blueprints for the development of a UR-rarity aircraft. Used in the Gear Lab.",
		sort_priority = 2,
		name = "UR Aircraft Design Plans",
		expired_date = "",
		item_transform_resource_num = 800,
		grid_num = 1,
		usage = "usage_drop_appointed",
		open_box = "",
		item_transform_num = 1,
		id = 2121,
		icon = "Props/Wshejitucai",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			{
				2,
				18118,
				1
			},
			{
				2,
				18120,
				1
			},
			{
				2,
				18122,
				1
			},
			{
				2,
				18124,
				1
			}
		},
		item_origin = {}
	},
	[100011] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 6. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Caribbean Sea A",
		expired_date = "",
		item_transform_resource_num = 160,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100011,
		icon = "Props/Wluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100012] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 5. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Caribbean Sea B",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100012,
		icon = "Props/Wluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100013] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 5. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Caribbean Sea C",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100013,
		icon = "Props/Wluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100014] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Caribbean Sea D",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100014,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100021] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean SW Sector A",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100021,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100023] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean SW Sector C",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100023,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100024] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean SW Sector D",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100024,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100025] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean SW Sector E",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100025,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100031] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Southwest Ocean Ridge A",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100031,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100032] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Southwest Ocean Ridge B",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100032,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100033] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Southwest Ocean Ridge C",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100033,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100034] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Southwest Ocean Ridge D",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100034,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100041] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: West Continental Shelf A",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100041,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100042] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: West Continental Shelf B",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100042,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100043] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: West Continental Shelf C",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100043,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100051] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Southeast Ocean Ridge A",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100051,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100052] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Southeast Ocean Ridge B",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100052,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100053] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Southeast Ocean Ridge C",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100053,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100054] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Southeast Ocean Ridge D",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100054,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100061] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean SE Sector A",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100061,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100062] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean SE Sector B",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100062,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100063] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean SE Sector C",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100063,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100064] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean SE Sector D",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100064,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100065] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean SE Sector E",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100065,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100066] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean SE Sector F",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100066,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100071] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 5. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Méditerranée A",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100071,
		icon = "Props/Wluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100072] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 6. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Méditerranée B",
		expired_date = "",
		item_transform_resource_num = 160,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100072,
		icon = "Props/Wluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100073] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 5. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Méditerranée C",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100073,
		icon = "Props/Wluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100081] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean W Sector A",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100081,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100082] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean W Sector B",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100082,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100083] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean W Sector C",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100083,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100084] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean W Sector D",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100084,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100085] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean W Sector E",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100085,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100091] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean NW Sector A",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100091,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100092] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean NW Sector B",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100092,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100093] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean NW Sector C",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100093,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100094] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean NW Sector D",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100094,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100095] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean NW Sector E",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100095,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100101] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 5. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Northwest Passage A",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100101,
		icon = "Props/Wluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100102] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 5. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Northwest Passage B",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100102,
		icon = "Props/Wluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100103] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Northwest Passage C",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100103,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100104] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Northwest Passage D",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100104,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100105] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Northwest Passage E",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100105,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100106] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 6. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Northwest Passage F",
		expired_date = "",
		item_transform_resource_num = 160,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100106,
		icon = "Props/Wluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100111] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean E Sector A",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100111,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100112] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean E Sector B",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100112,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100113] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean E Sector C",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100113,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100114] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean E Sector D",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100114,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100121] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 6. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: East Continental Shelf A",
		expired_date = "",
		item_transform_resource_num = 160,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100121,
		icon = "Props/Wluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100122] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: East Continental Shelf B",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100122,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100123] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: East Continental Shelf C",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100123,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100124] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 5. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: East Continental Shelf D",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100124,
		icon = "Props/Wluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100125] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: East Continental Shelf E",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100125,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100131] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean NE Sector A",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100131,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100132] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean NE Sector B",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100132,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100133] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean NE Sector C",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100133,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100134] = {
		rarity = 2,
		display = "Coordinates to a zone with a Corrosion level of 2. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean NE Sector D",
		expired_date = "",
		item_transform_resource_num = 10,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100134,
		icon = "Props/Wluopanjihuo2",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100135] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean NE Sector E",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100135,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100141] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Northeast Passage A",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100141,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100142] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 4. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Northeast Passage B",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100142,
		icon = "Props/Wluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100143] = {
		rarity = 3,
		display = "Coordinates to a zone with a Corrosion level of 3. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Northeast Passage C",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100143,
		icon = "Props/Wluopanjihuo3",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			7
		}
	},
	[100144] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 5. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: Northeast Passage D",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100144,
		icon = "Props/Wluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100151] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 5. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean Depths A",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100151,
		icon = "Props/Wluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100152] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 5. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean Depths B",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100152,
		icon = "Props/Wluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100153] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 6. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean Depths C",
		expired_date = "",
		item_transform_resource_num = 160,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100153,
		icon = "Props/Wluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100155] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 6. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean Depths D",
		expired_date = "",
		item_transform_resource_num = 160,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100155,
		icon = "Props/Wluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100156] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 6. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean Depths E",
		expired_date = "",
		item_transform_resource_num = 160,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100156,
		icon = "Props/Wluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100157] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 6. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean Depths F",
		expired_date = "",
		item_transform_resource_num = 160,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100157,
		icon = "Props/Wsairenluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100158] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 5. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean Depths G",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100158,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[100159] = {
		rarity = 4,
		display = "Coordinates to a zone with a Corrosion level of 5. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Map Coordinates: NA Ocean Depths H",
		expired_date = "",
		item_transform_resource_num = 80,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 100159,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[110011] = {
		rarity = 5,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Caribbean Sea A",
		expired_date = "",
		item_transform_resource_num = 800,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110011,
		icon = "Props/Wsairenluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			201,
			7
		}
	},
	[110012] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Caribbean Sea B",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110012,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[110013] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Caribbean Sea C",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110013,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[110014] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Caribbean Sea D",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110014,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110042] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: West Continental Shelf B",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110042,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110051] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Southeast Ocean Ridge A",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110051,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110052] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Southeast Ocean Ridge B",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110052,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110053] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Southeast Ocean Ridge C",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110053,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110054] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Southeast Ocean Ridge D",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110054,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110061] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean SE Sector A",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110061,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110063] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean SE Sector C",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110063,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110064] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean SE Sector D",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110064,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110071] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Méditerranée A",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110071,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[110072] = {
		rarity = 5,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Méditerranée B",
		expired_date = "",
		item_transform_resource_num = 800,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110072,
		icon = "Props/Wsairenluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			201,
			7
		}
	},
	[110073] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Méditerranée C",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110073,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[110082] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean W Sector B",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110082,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110085] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean W Sector E",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110085,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110091] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean NW Sector A",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110091,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110101] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Northwest Passage A",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110101,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[110102] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Northwest Passage B",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110102,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[110103] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Northwest Passage C",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110103,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110104] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Northwest Passage D",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110104,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110106] = {
		rarity = 5,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Northwest Passage F",
		expired_date = "",
		item_transform_resource_num = 800,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110106,
		icon = "Props/Wsairenluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			201,
			7
		}
	},
	[110121] = {
		rarity = 5,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: East Continental Shelf A",
		expired_date = "",
		item_transform_resource_num = 800,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110121,
		icon = "Props/Wsairenluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			201,
			7
		}
	},
	[110124] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: East Continental Shelf D",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110124,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[110142] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Northeast Passage B",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110142,
		icon = "Props/Wsairenluopanjihuo4",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			7
		}
	},
	[110144] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: Northeast Passage D",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110144,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[110151] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean Depths A",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110151,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[110152] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean Depths B",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110152,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[110153] = {
		rarity = 5,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean Depths C",
		expired_date = "",
		item_transform_resource_num = 800,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110153,
		icon = "Props/Wsairenluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			201,
			7
		}
	},
	[110155] = {
		rarity = 5,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean Depths D",
		expired_date = "",
		item_transform_resource_num = 800,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110155,
		icon = "Props/Wsairenluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			201,
			7
		}
	},
	[110156] = {
		rarity = 5,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean Depths E",
		expired_date = "",
		item_transform_resource_num = 800,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110156,
		icon = "Props/Wsairenluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			201,
			7
		}
	},
	[110157] = {
		rarity = 5,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean Depths F",
		expired_date = "",
		item_transform_resource_num = 800,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110157,
		icon = "Props/Wsairenluopanjihuo6",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			201,
			7
		}
	},
	[110158] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean Depths G",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110158,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[110159] = {
		rarity = 4,
		display = "Coordinates to a zone where a dangerous Siren has been sighted. Will disappear once you arrive at the destination.",
		sort_priority = 10,
		name = "Siren Coordinates: NA Ocean Depths H",
		expired_date = "",
		item_transform_resource_num = 400,
		grid_num = 0,
		usage = "usage_world_map",
		open_box = "",
		item_transform_num = 1,
		id = 110159,
		icon = "Props/Wsairenluopanjihuo5",
		log_text = "",
		item_transform_resource = 3002,
		usage_arg = {
			1
		},
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[2000000] = {
		rarity = 3,
		display = "A rigging attachment that changes the battlefield conditions during Operation Siren. Affects the Offense stat of enemy ships.",
		sort_priority = 10,
		name = "Adaptive Tuning - Offense",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2000000,
		icon = "Props/Wbuff1",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			5,
			6
		}
	},
	[2000001] = {
		rarity = 3,
		display = "A rigging attachment that changes the battlefield conditions during Operation Siren. Affects the Survivability stat of enemy ships.",
		sort_priority = 10,
		name = "Adaptive Tuning - Survivability",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2000001,
		icon = "Props/Wbuff2",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			5,
			6
		}
	},
	[2000002] = {
		rarity = 3,
		display = "A rigging attachment that changes the battlefield conditions during Operation Siren. Affects your ship's healing abilities.",
		sort_priority = 10,
		name = "Adaptive Tuning - Tactics",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2000002,
		icon = "Props/Wbuff3",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			5,
			6
		}
	},
	[2000003] = {
		rarity = 4,
		display = "A rigging attachment that changes the battlefield conditions during Operation Siren. Affects the Offense stat of enemy ships.",
		sort_priority = 10,
		name = "Adaptive Tuning - Offense",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2000003,
		icon = "Props/Wbuff1",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			5,
			6
		}
	},
	[2000004] = {
		rarity = 4,
		display = "A rigging attachment that changes the battlefield conditions during Operation Siren. Affects the Survivability stat of enemy ships.",
		sort_priority = 10,
		name = "Adaptive Tuning - Survivability",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2000004,
		icon = "Props/Wbuff2",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			5,
			6
		}
	},
	[2000005] = {
		rarity = 4,
		display = "A rigging attachment that changes the battlefield conditions during Operation Siren. Affects your ship's healing abilities.",
		sort_priority = 10,
		name = "Adaptive Tuning - Tactics",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2000005,
		icon = "Props/Wbuff3",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			5,
			6
		}
	},
	[2000006] = {
		rarity = 2,
		display = "Can be exchanged for items in the Operation Siren store. Any unspent coins will converted into Supply Shop Vouchers when operation progress resets.",
		sort_priority = 10,
		name = "Operation Supply Coins",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2000006,
		icon = "Props/Wdashijiehuobi",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			201,
			3,
			4,
			5,
			6,
			7
		}
	},
	[2000007] = {
		rarity = 3,
		display = "Can be exchanged for items in the Operation Siren store. Any unspent coins will be converted into Supply Shop Vouchers when operation progress resets.",
		sort_priority = 10,
		name = "Operation Supply Coins",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2000007,
		icon = "Props/Wdashijiehuobi",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			201,
			3,
			4,
			5,
			6,
			7
		}
	},
	[2000008] = {
		rarity = 2,
		display = "Can be used to restore 20 Action Points.",
		sort_priority = 10,
		name = "Action Point Refill (S)",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2000008,
		icon = "Props/Wxingdonglihuifu1",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			100,
			201,
			4,
			7
		}
	},
	[2000009] = {
		rarity = 2,
		display = "(Current) Can be used to restore the HP of 1 ship in your current fleet by 1,000.",
		sort_priority = 10,
		name = "Emergency Repair Pack",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_world_healing_value",
		open_box = "",
		item_transform_num = 0,
		id = 2000009,
		icon = "Props/Wshengminghuifu1",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			100,
			201,
			3,
			7
		}
	},
	[2100001] = {
		rarity = 3,
		display = "A strange device that has logged the coordinates to a zone with a Corrosion level of 4.",
		sort_priority = 1,
		name = "Coordinate Logger",
		expired_date = "",
		item_transform_resource_num = 20,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 1,
		usage_arg = "1000021",
		id = 2100001,
		icon = "Props/Wluopanputong",
		log_text = "",
		item_transform_resource = 3002,
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[2100002] = {
		rarity = 4,
		display = "A strange device that has logged the coordinates to a zone with a Corrosion level of 4-6.",
		sort_priority = 1,
		name = "Coordinate Logger",
		expired_date = "",
		item_transform_resource_num = 40,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 1,
		usage_arg = "1000022",
		id = 2100002,
		icon = "Props/Wluopanputong",
		log_text = "",
		item_transform_resource = 3002,
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[2100003] = {
		rarity = 5,
		display = "A strange device that has logged the coordinates to a zone where a Siren incursion has been spotted, with a Corrosion level of 4-6.",
		sort_priority = 1,
		name = "Siren Coordinate Logger",
		expired_date = "",
		item_transform_resource_num = 200,
		grid_num = 1,
		usage = "usage_drop",
		open_box = "",
		item_transform_num = 1,
		usage_arg = "1000023",
		id = 2100003,
		icon = "Props/Wsairenluopanputong",
		log_text = "",
		item_transform_resource = 3002,
		item_origin = {
			100,
			101,
			201,
			7
		}
	},
	[2100011] = {
		rarity = 2,
		display = "Contains a random Rare building material.",
		sort_priority = 2,
		name = "T1 Development Materials Container",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2100011,
		icon = "Props/Wsucaixiang3",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			100,
			201,
			7,
			8,
			9,
			10,
			11
		}
	},
	[2100012] = {
		rarity = 3,
		display = "Contains a random Elite building material.",
		sort_priority = 2,
		name = "T2 Development Materials Container",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2100012,
		icon = "Props/Wsucaixiang2",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			100,
			201,
			7,
			8,
			9,
			10,
			11
		}
	},
	[2100013] = {
		rarity = 4,
		display = "Contains a random Super Rare building material.",
		sort_priority = 2,
		name = "T3 Development Materials Container",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2100013,
		icon = "Props/Wsucaixiang1",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			100,
			201,
			7,
			8,
			9,
			10,
			11
		}
	},
	[2100014] = {
		rarity = 4,
		display = "Contains a random Super Rare weapon design. Used in the Gear Lab.",
		sort_priority = 2,
		name = "SR Weapon Design Plans",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2100014,
		icon = "Props/Wshejitujin",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			100,
			201,
			7,
			8,
			9,
			10,
			11
		}
	},
	[2100015] = {
		rarity = 5,
		display = "Contains a random Ultra Rare weapon design. Used in the Gear Lab.",
		sort_priority = 2,
		name = "UR Weapon Design Plans",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2100015,
		icon = "Props/Wshejitucai",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {}
	},
	[2100021] = {
		rarity = 4,
		display = "Contains a random Super Rare gear part.",
		sort_priority = 2,
		name = "T4 Random Gear Part",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2100021,
		icon = "Props/Wsuijibujian",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			100,
			201,
			7,
			8,
			9,
			10,
			11
		}
	},
	[2100022] = {
		rarity = 4,
		display = "Upgrade material used to further enhance gear of Super Rare rarity or below.",
		sort_priority = 2,
		name = "Prototype Gear Upgrade Part",
		expired_date = "",
		item_transform_resource_num = 0,
		grid_num = 1,
		usage = "usage_undefined",
		open_box = "",
		item_transform_num = 0,
		id = 2100022,
		icon = "Props/17990",
		log_text = "",
		item_transform_resource = 0,
		usage_arg = {},
		item_origin = {
			100,
			201,
			7,
			8,
			9,
			10,
			11
		}
	},
	all = {
		100,
		101,
		102,
		110,
		201,
		202,
		203,
		204,
		205,
		206,
		251,
		252,
		253,
		301,
		302,
		303,
		304,
		305,
		306,
		2002,
		2003,
		2004,
		2005,
		2006,
		2014,
		2015,
		2016,
		2101,
		2102,
		2103,
		2111,
		2112,
		2113,
		2114,
		2115,
		2116,
		2117,
		2118,
		2119,
		2120,
		2121,
		100011,
		100012,
		100013,
		100014,
		100021,
		100023,
		100024,
		100025,
		100031,
		100032,
		100033,
		100034,
		100041,
		100042,
		100043,
		100051,
		100052,
		100053,
		100054,
		100061,
		100062,
		100063,
		100064,
		100065,
		100066,
		100071,
		100072,
		100073,
		100081,
		100082,
		100083,
		100084,
		100085,
		100091,
		100092,
		100093,
		100094,
		100095,
		100101,
		100102,
		100103,
		100104,
		100105,
		100106,
		100111,
		100112,
		100113,
		100114,
		100121,
		100122,
		100123,
		100124,
		100125,
		100131,
		100132,
		100133,
		100134,
		100135,
		100141,
		100142,
		100143,
		100144,
		100151,
		100152,
		100153,
		100155,
		100156,
		100157,
		100158,
		100159,
		110011,
		110012,
		110013,
		110014,
		110042,
		110051,
		110052,
		110053,
		110054,
		110061,
		110063,
		110064,
		110071,
		110072,
		110073,
		110082,
		110085,
		110091,
		110101,
		110102,
		110103,
		110104,
		110106,
		110121,
		110124,
		110142,
		110144,
		110151,
		110152,
		110153,
		110155,
		110156,
		110157,
		110158,
		110159,
		2000000,
		2000001,
		2000002,
		2000003,
		2000004,
		2000005,
		2000006,
		2000007,
		2000008,
		2000009,
		2100001,
		2100002,
		2100003,
		2100011,
		2100012,
		2100013,
		2100014,
		2100015,
		2100021,
		2100022
	}
}
