pg = pg or {}
pg.memory_template = {
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "索敵與“冰棒”",
		condition = "序章",
		story = "S001",
		id = 1,
		icon = "default",
		is_open = 1
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "遭遇",
		condition = "序章",
		story = "S002",
		id = 2,
		icon = "default",
		is_open = 1
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "「皇家艦隊的榮耀」",
		condition = "序章",
		story = "S007",
		id = 3,
		icon = "default",
		is_open = 1
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "衝突",
		condition = "序章",
		story = "S006",
		id = 4,
		icon = "default",
		is_open = 1
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "「萊茵演習」",
		condition = "序章",
		story = "S003",
		id = 5,
		icon = "default",
		is_open = 1
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "結束、與開始",
		condition = "序章",
		story = "S004",
		id = 6,
		icon = "default",
		is_open = 1
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "序幕-大黃蜂",
		condition = "與主線1-1 BOSS交戰",
		story = "T10101",
		id = 7,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "序幕-警報",
		condition = "通關主線1-1",
		story = "T10102",
		id = 8,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "一章-燃燒的海面",
		condition = "進入主線1-2",
		story = "UI10201",
		id = 9,
		icon = "memorybg_1",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "一章-突破封鎖",
		condition = "進入主線1-2",
		story = "UI10202",
		id = 10,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "一章-迎擊",
		condition = "與主線1-2 BOSS交戰",
		story = "T10201",
		id = 11,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "一章-首戰勝利",
		condition = "通關主線1-2",
		story = "T10202",
		id = 12,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "一章-來犯之敵",
		condition = "與主線1-3 BOSS交戰",
		story = "T10301",
		id = 13,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "一章-深入調查",
		condition = "通關主線1-3",
		story = "T10302",
		id = 14,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "一章-重櫻強敵",
		condition = "與主線1-4 BOSS交戰",
		story = "T10401",
		id = 15,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "一章-赤色中軸",
		condition = "通關主線1-4",
		story = "T10402",
		id = 16,
		icon = "memorybg_2",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "二章-珊瑚之海",
		condition = "到達第二章",
		story = "UI20101",
		id = 17,
		icon = "memorybg_3",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "二章-反擊的序曲",
		condition = "通關主線2-2",
		story = "T20201",
		id = 18,
		icon = "memorybg_4",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "二章-再下一城",
		condition = "通關主線2-3",
		story = "T20301",
		id = 19,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "三章-命運的五分鐘",
		condition = "到達第三章",
		story = "UI30101",
		id = 20,
		icon = "memorybg_2",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "三章-遇敵",
		condition = "進入主線3-1",
		story = "T30101",
		id = 21,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "三章-交戰",
		condition = "與主線3-1 BOSS交戰",
		story = "T30102",
		id = 22,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "三章-戰勝",
		condition = "通關主線3-1",
		story = "T30103",
		id = 23,
		icon = "memorybg_5",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "三章-敵機",
		condition = "與主線3-2 BOSS交戰",
		story = "T30201",
		id = 24,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "三章-宿命",
		condition = "通關主線3-2",
		story = "T30202",
		id = 25,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "三章-絕筆",
		condition = "通關主線3-3",
		story = "T30301",
		id = 26,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "三章-最後的反擊",
		condition = "與主線3-4 BOSS交戰",
		story = "T30401",
		id = 27,
		icon = "default",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "三章-傳承的意志",
		condition = "通關主線3-4",
		story = "T30402",
		id = 28,
		icon = "memorybg_6",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "努力、希望和計畫",
		condition = "進入戰役「努力、希望和計畫」",
		story = "UIACT10000",
		id = 29,
		icon = "activity",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "不祥的疑雲",
		condition = "進入戰役「努力、希望和計畫」SP.1",
		story = "TACT10001",
		id = 30,
		icon = "activity",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "Z艦隊的反擊",
		condition = "進入戰役「努力、希望和計畫」SP.2",
		story = "TACT10002",
		id = 31,
		icon = "activity",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "終局1",
		condition = "通關戰役「努力、希望和計畫」SP.2",
		story = "TACT10003",
		id = 32,
		icon = "activity",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "大艦巨炮的輓歌",
		condition = "進入戰役「努力、希望和計畫」SP.3",
		story = "TACT10004",
		id = 33,
		icon = "activity",
		is_open = 0
	},
	{
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "終局2",
		condition = "通關戰役「努力、希望和計畫」SP.3",
		story = "TACT10005",
		id = 34,
		icon = "activity",
		is_open = 0
	},
	[62] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託1",
		condition = "接取{namecode:98}任務1",
		story = "AKASHI1",
		id = 62,
		icon = "activity",
		is_open = 0
	},
	[63] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託2",
		condition = "接取{namecode:98}任務2",
		story = "AKASHI2",
		id = 63,
		icon = "activity",
		is_open = 0
	},
	[64] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託3",
		condition = "接取{namecode:98}任務3",
		story = "AKASHI3",
		id = 64,
		icon = "activity",
		is_open = 0
	},
	[65] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託4",
		condition = "接取{namecode:98}任務4",
		story = "AKASHI4",
		id = 65,
		icon = "activity",
		is_open = 0
	},
	[66] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託5-1",
		condition = "接取{namecode:98}任務5 I",
		story = "AKASHI5",
		id = 66,
		icon = "activity",
		is_open = 0
	},
	[67] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託5-2",
		condition = "接取{namecode:98}任務5 II",
		story = "AKASHI51",
		id = 67,
		icon = "activity",
		is_open = 0
	},
	[68] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託6-1",
		condition = "接取{namecode:98}任務6 I",
		story = "AKASHI6",
		id = 68,
		icon = "activity",
		is_open = 0
	},
	[69] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託6-2",
		condition = "接取{namecode:98}任務6 II",
		story = "AKASHI62",
		id = 69,
		icon = "activity",
		is_open = 0
	},
	[70] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託6-3",
		condition = "接取{namecode:98}任務6 III",
		story = "AKASHI63",
		id = 70,
		icon = "activity",
		is_open = 0
	},
	[71] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託6-4",
		condition = "接取{namecode:98}任務6 IV",
		story = "AKASHI64",
		id = 71,
		icon = "activity",
		is_open = 0
	},
	[72] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託7-1",
		condition = "接取{namecode:98}任務7 I",
		story = "AKASHI7",
		id = 72,
		icon = "activity",
		is_open = 0
	},
	[73] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託7-2",
		condition = "接取{namecode:98}任務7 II",
		story = "AKASHI72",
		id = 73,
		icon = "activity",
		is_open = 0
	},
	[74] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託8-1",
		condition = "接取{namecode:98}任務8 I",
		story = "AKASHI8",
		id = 74,
		icon = "activity",
		is_open = 0
	},
	[75] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託8-2",
		condition = "接取{namecode:98}任務8 II",
		story = "AKASHI82",
		id = 75,
		icon = "activity",
		is_open = 0
	},
	[76] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託8-3",
		condition = "接取{namecode:98}任務8 III",
		story = "AKASHI83",
		id = 76,
		icon = "activity",
		is_open = 0
	},
	[77] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託8-4",
		condition = "接取{namecode:98}任務8 IV",
		story = "AKASHI84",
		id = 77,
		icon = "activity",
		is_open = 0
	},
	[78] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託8-5",
		condition = "接取{namecode:98}任務8 V",
		story = "AKASHI85",
		id = 78,
		icon = "activity",
		is_open = 0
	},
	[79] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託8-6",
		condition = "接取{namecode:98}任務8 VI",
		story = "AKASHI86",
		id = 79,
		icon = "activity",
		is_open = 0
	},
	[80] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託9",
		condition = "接取{namecode:98}任務9",
		story = "AKASHI9",
		id = 80,
		icon = "activity",
		is_open = 0
	},
	[81] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:98}的委託10",
		condition = "接取{namecode:98}任務10",
		story = "AKASHI10",
		id = 81,
		icon = "activity",
		is_open = 0
	},
	[114] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "序",
		condition = "開始『紅染的參訪者』·上",
		story = "GUOQING1",
		id = 114,
		icon = "activity",
		is_open = 0
	},
	[115] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "風暴的盡頭·上",
		condition = "進入『紅染的參訪者』A1/C1",
		story = "GUOQING3",
		id = 115,
		icon = "activity",
		is_open = 0
	},
	[116] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "風暴的盡頭·下",
		condition = "發現『紅染的參訪者』A1/C1 BOSS",
		story = "GUOQING4",
		id = 116,
		icon = "activity",
		is_open = 0
	},
	[117] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "間章",
		condition = "通關『紅染的參訪者』A1/C1",
		story = "GUOQING5",
		id = 117,
		icon = "activity",
		is_open = 0
	},
	[118] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "求救信號的彼方·上",
		condition = "進入『紅染的參訪者』A2/C2",
		story = "GUOQING6",
		id = 118,
		icon = "activity",
		is_open = 0
	},
	[119] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "求救信號的彼方·下",
		condition = "發現『紅染的參訪者』A2/C2 BOSS",
		story = "GUOQING7",
		id = 119,
		icon = "activity",
		is_open = 0
	},
	[120] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "回想",
		condition = "進入『紅染的參訪者』A3/C3",
		story = "GUOQING8",
		id = 120,
		icon = "activity",
		is_open = 0
	},
	[121] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "聖域的護衛·上",
		condition = "發現『紅染的參訪者』A3/C3 BOSS",
		story = "GUOQING9",
		id = 121,
		icon = "activity",
		is_open = 0
	},
	[122] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "聖域的護衛·下",
		condition = "通關『紅染的參訪者』A3/C3",
		story = "GUOQING10",
		id = 122,
		icon = "activity",
		is_open = 0
	},
	[123] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "間章-2",
		condition = "開始『紅染的參訪者·下』",
		story = "GUOQING11",
		id = 123,
		icon = "activity",
		is_open = 0
	},
	[124] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "“幸運”艦·上",
		condition = "發現『紅染的參訪者』B1/D1 BOSS",
		story = "GUOQING12",
		id = 124,
		icon = "activity",
		is_open = 0
	},
	[125] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "“幸運”艦·下",
		condition = "通關『紅染的參訪者』B1/D1",
		story = "GUOQING13",
		id = 125,
		icon = "activity",
		is_open = 0
	},
	[126] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "“姐妹”的羈絆·上",
		condition = "進入『紅染的參訪者』B2/D2",
		story = "GUOQING14",
		id = 126,
		icon = "activity",
		is_open = 0
	},
	[127] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "“姐妹”的羈絆·中",
		condition = "發現『紅染的參訪者』B2/D2 BOSS",
		story = "GUOQING15",
		id = 127,
		icon = "activity",
		is_open = 0
	},
	[128] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "“姐妹”的羈絆·下",
		condition = "通關『紅染的參訪者』B2/D2",
		story = "GUOQING16",
		id = 128,
		icon = "activity",
		is_open = 0
	},
	[129] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "紅染的守護者·上",
		condition = "進入『紅染的參訪者』B3/D3",
		story = "GUOQING17",
		id = 129,
		icon = "activity",
		is_open = 0
	},
	[130] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "紅染的守護者·中",
		condition = "發現『紅染的參訪者』B3/D3 BOSS",
		story = "GUOQING18",
		id = 130,
		icon = "activity",
		is_open = 0
	},
	[131] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "紅染的守護者·下",
		condition = "通關『紅染的參訪者』B3/D3",
		story = "GUOQING19",
		id = 131,
		icon = "activity",
		is_open = 0
	},
	[142] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "魔女、永保純真",
		condition = "解鎖萬聖節任務1",
		story = "WANSHENGJIE1",
		id = 142,
		icon = "wanshengjie",
		is_open = 0
	},
	[143] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "Gold、開始行動",
		condition = "解鎖萬聖節任務2",
		story = "WANSHENGJIE2",
		id = 143,
		icon = "wanshengjie",
		is_open = 0
	},
	[144] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "深夜的惡作劇",
		condition = "解鎖萬聖節任務3",
		story = "WANSHENGJIE3",
		id = 144,
		icon = "wanshengjie",
		is_open = 0
	},
	[145] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "消失的南瓜派",
		condition = "解鎖萬聖節任務4",
		story = "WANSHENGJIE4",
		id = 145,
		icon = "wanshengjie",
		is_open = 0
	},
	[146] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "Trick or treat！",
		condition = "解鎖萬聖節任務5",
		story = "WANSHENGJIE5",
		id = 146,
		icon = "wanshengjie",
		is_open = 0
	},
	[147] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "顯露身形的幽靈",
		condition = "解鎖萬聖節任務6",
		story = "WANSHENGJIE6",
		id = 147,
		icon = "wanshengjie",
		is_open = 0
	},
	[148] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "南瓜艦隊，出擊！",
		condition = "解鎖萬聖節任務7",
		story = "WANSHENGJIE7",
		id = 148,
		icon = "wanshengjie",
		is_open = 0
	},
	[163] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "攝影大會！",
		condition = "解鎖聖誕任務1",
		story = "SHENGDAN01",
		id = 163,
		icon = "christmas",
		is_open = 0
	},
	[164] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "聖誕牙哥！",
		condition = "解鎖聖誕任務2",
		story = "SHENGDAN02",
		id = 164,
		icon = "christmas",
		is_open = 0
	},
	[165] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "重櫻的聖誕節·上",
		condition = "解鎖聖誕任務3",
		story = "SHENGDAN03",
		id = 165,
		icon = "christmas",
		is_open = 0
	},
	[166] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "重櫻的聖誕節·下",
		condition = "解鎖聖誕任務4",
		story = "SHENGDAN04",
		id = 166,
		icon = "christmas",
		is_open = 0
	},
	[167] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "大家的聖誕老人",
		condition = "解鎖聖誕任務5",
		story = "SHENGDAN05",
		id = 167,
		icon = "christmas",
		is_open = 0
	},
	[168] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "聖夜的大餐",
		condition = "解鎖聖誕任務6",
		story = "SHENGDAN06",
		id = 168,
		icon = "christmas",
		is_open = 0
	},
	[169] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "聖夜的擁抱",
		condition = "解鎖聖誕任務7",
		story = "SHENGDAN07",
		id = 169,
		icon = "christmas",
		is_open = 0
	},
	[170] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "Merry Christmas",
		condition = "解鎖聖誕任務8",
		story = "SHENGDAN08",
		id = 170,
		icon = "christmas",
		is_open = 0
	},
	[214] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "某個早晨的突發事件",
		condition = "解鎖「春風的十字星」DAY1",
		story = "XIAOTIANE1",
		id = 214,
		icon = "memory_xiaotiane",
		is_open = 0
	},
	[215] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "中斷的線索",
		condition = "解鎖「春風的十字星」DAY2",
		story = "XIAOTIANE2",
		id = 215,
		icon = "memory_xiaotiane",
		is_open = 0
	},
	[216] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "嫌疑與詢問",
		condition = "解鎖「春風的十字星」DAY3",
		story = "XIAOTIANE3",
		id = 216,
		icon = "memory_xiaotiane",
		is_open = 0
	},
	[217] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "現行犯？",
		condition = "解鎖「春風的十字星」DAY5",
		story = "XIAOTIANE4",
		id = 217,
		icon = "memory_xiaotiane",
		is_open = 0
	},
	[218] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "辯解",
		condition = "解鎖「春風的十字星」DAY7",
		story = "XIAOTIANE5",
		id = 218,
		icon = "memory_xiaotiane",
		is_open = 0
	},
	[219] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "證人",
		condition = "解鎖「春風的十字星」DAY9",
		story = "XIAOTIANE6",
		id = 219,
		icon = "memory_xiaotiane",
		is_open = 0
	},
	[220] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "結案",
		condition = "解鎖「春風的十字星」DAY10",
		story = "XIAOTIANE7",
		id = 220,
		icon = "memory_xiaotiane",
		is_open = 0
	},
	[246] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:96}的早晨",
		condition = "解鎖{namecode:96}劇情任務1",
		story = "RUIHE1",
		id = 246,
		icon = "chara_ruihe",
		is_open = 0
	},
	[247] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:96}與小夥伴們",
		condition = "解鎖{namecode:96}劇情任務2",
		story = "RUIHE2",
		id = 247,
		icon = "chara_ruihe",
		is_open = 0
	},
	[248] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:96}與前輩們",
		condition = "解鎖{namecode:96}劇情任務3",
		story = "RUIHE3",
		id = 248,
		icon = "chara_ruihe",
		is_open = 0
	},
	[249] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "{namecode:96}與大前輩",
		condition = "解鎖{namecode:96}劇情任務4",
		story = "RUIHE4",
		id = 249,
		icon = "chara_ruihe",
		is_open = 0
	},
	[250] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "今天料理我負責！",
		condition = "解鎖{namecode:96}劇情任務5",
		story = "RUIHE5",
		id = 250,
		icon = "chara_ruihe",
		is_open = 0
	},
	[251] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "深夜的談話",
		condition = "解鎖{namecode:96}劇情任務6",
		story = "RUIHE6",
		id = 251,
		icon = "chara_ruihe",
		is_open = 0
	},
	[252] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "不屈之鶴",
		condition = "解鎖{namecode:96}劇情任務7",
		story = "RUIHE7",
		id = 252,
		icon = "chara_ruihe",
		is_open = 0
	},
	[407] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "博物館、崩壞",
		condition = "解鎖「{namecode:82}前輩的收藏大公開」任務1",
		story = "SANLICHUANMO1",
		id = 407,
		icon = "memory_sanlichuanmo",
		is_open = 0
	},
	[408] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "寬容的大前輩",
		condition = "解鎖「{namecode:82}前輩的收藏大公開」任務2",
		story = "SANLICHUANMO2",
		id = 408,
		icon = "memory_sanlichuanmo",
		is_open = 0
	},
	[409] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "努力的後輩們",
		condition = "解鎖「{namecode:82}前輩的收藏大公開」任務3",
		story = "SANLICHUANMO3",
		id = 409,
		icon = "memory_sanlichuanmo",
		is_open = 0
	},
	[410] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "新生{namecode:82}博物館，開放！",
		condition = "解鎖「{namecode:82}前輩的收藏大公開」任務4",
		story = "SANLICHUANMO4",
		id = 410,
		icon = "memory_sanlichuanmo",
		is_open = 0
	},
	[411] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "好心情的秘書艦",
		condition = "解鎖「{namecode:71}的宴會」任務1",
		story = "BIRUI1",
		id = 411,
		icon = "memory_birui",
		is_open = 0
	},
	[412] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "邀請函",
		condition = "解鎖「{namecode:71}的宴會」任務2",
		story = "BIRUI2",
		id = 412,
		icon = "memory_birui",
		is_open = 0
	},
	[413] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "緣由",
		condition = "解鎖「{namecode:71}的宴會」任務3",
		story = "BIRUI3",
		id = 413,
		icon = "memory_birui",
		is_open = 0
	},
	[414] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "準備",
		condition = "解鎖「{namecode:71}的宴會」任務4",
		story = "BIRUI4",
		id = 414,
		icon = "memory_birui",
		is_open = 0
	},
	[415] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "宴會·上",
		condition = "解鎖「{namecode:71}的宴會」任務5",
		story = "BIRUI5",
		id = 415,
		icon = "memory_birui",
		is_open = 0
	},
	[416] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "宴會·下",
		condition = "解鎖「{namecode:71}的宴會」任務6",
		story = "BIRUI6",
		id = 416,
		icon = "memory_birui",
		is_open = 0
	},
	[417] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "心聲",
		condition = "解鎖「{namecode:71}的宴會」任務7",
		story = "BIRUI7",
		id = 417,
		icon = "memory_birui",
		is_open = 0
	},
	[494] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "去尋找迷路的幽靈吧！",
		condition = "解鎖「搗蛋萬聖夜！」任務1",
		story = "BEILIWANSHENGJIE1",
		id = 494,
		icon = "memory_beiliwanshengjie",
		is_open = 0
	},
	[495] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "好奇的魔女",
		condition = "解鎖「搗蛋萬聖夜！」任務2",
		story = "BEILIWANSHENGJIE2",
		id = 495,
		icon = "memory_beiliwanshengjie",
		is_open = 0
	},
	[496] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "害怕幽靈的魔女",
		condition = "解鎖「搗蛋萬聖夜！」任務3",
		story = "BEILIWANSHENGJIE3",
		id = 496,
		icon = "memory_beiliwanshengjie",
		is_open = 0
	},
	[497] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "嫌麻煩的魔女",
		condition = "解鎖「搗蛋萬聖夜！」任務4",
		story = "BEILIWANSHENGJIE4",
		id = 497,
		icon = "memory_beiliwanshengjie",
		is_open = 0
	},
	[498] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "棺材裡的幫手？",
		condition = "解鎖「搗蛋萬聖夜！」任務5",
		story = "BEILIWANSHENGJIE5",
		id = 498,
		icon = "memory_beiliwanshengjie",
		is_open = 0
	},
	[499] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "幽靈追擊隊！",
		condition = "解鎖「搗蛋萬聖夜！」任務6",
		story = "BEILIWANSHENGJIE6",
		id = 499,
		icon = "memory_beiliwanshengjie",
		is_open = 0
	},
	[500] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "萬聖夜快樂！",
		condition = "解鎖「搗蛋萬聖夜！」任務7",
		story = "BEILIWANSHENGJIE7",
		id = 500,
		icon = "memory_beiliwanshengjie",
		is_open = 0
	},
	[501] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "兔兔星是什麼？",
		condition = "解鎖「神秘的兔兔星人？！ 」任務1",
		story = "BEILI1",
		id = 501,
		icon = "memory_beili",
		is_open = 0
	},
	[502] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "兔兔星人特徵——“兔兔”！",
		condition = "解鎖「神秘的兔兔星人？！ 」任務2",
		story = "BEILI2",
		id = 502,
		icon = "memory_beili",
		is_open = 0
	},
	[503] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "兔兔星人特徵——“努力”！",
		condition = "解鎖「神秘的兔兔星人？！ 」任務3",
		story = "BEILI3",
		id = 503,
		icon = "memory_beili",
		is_open = 0
	},
	[504] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "兔兔星人特徵——“偶像”？",
		condition = "解鎖「神秘的兔兔星人？！ 」任務4",
		story = "BEILI4",
		id = 504,
		icon = "memory_beili",
		is_open = 0
	},
	[505] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "兔兔星人特徵——“愛心”！",
		condition = "解鎖「神秘的兔兔星人？！ 」任務5",
		story = "BEILI5",
		id = 505,
		icon = "memory_beili",
		is_open = 0
	},
	[506] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "兔兔星來客？！",
		condition = "解鎖「神秘的兔兔星人？！ 」任務6",
		story = "BEILI6",
		id = 506,
		icon = "memory_beili",
		is_open = 0
	},
	[507] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "真正的兔兔星人",
		condition = "解鎖「神秘的兔兔星人？！ 」任務7",
		story = "BEILI7",
		id = 507,
		icon = "memory_beili",
		is_open = 0
	},
	[10011] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "休假中的偶遇",
		condition = "完成長島任務1",
		story = "CHANGDAO1",
		id = 10011,
		icon = "changdao",
		is_open = 0
	},
	[10012] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "No more運動！",
		condition = "完成長島任務2",
		story = "CHANGDAO2",
		id = 10012,
		icon = "changdao",
		is_open = 0
	},
	[10013] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "No more鍛煉！",
		condition = "完成長島任務3",
		story = "CHANGDAO3",
		id = 10013,
		icon = "changdao",
		is_open = 0
	},
	[10014] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "正確的休假方式",
		condition = "完成長島任務4",
		story = "CHANGDAO4",
		id = 10014,
		icon = "changdao",
		is_open = 0
	},
	[10015] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "吃我必殺技啦！",
		condition = "完成長島任務5",
		story = "CHANGDAO5",
		id = 10015,
		icon = "changdao",
		is_open = 0
	},
	[10016] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "大·失·敗",
		condition = "完成長島任務6",
		story = "CHANGDAO6",
		id = 10016,
		icon = "changdao",
		is_open = 0
	},
	[10017] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 1,
		title = "別了，夢想中的休假",
		condition = "完成長島任務7",
		story = "CHANGDAO7",
		id = 10017,
		icon = "changdao",
		is_open = 0
	},
	[10018] = {
		mask = "bg/bg_memory",
		subtitle = "",
		type = 2,
		title = "歸來與新生",
		condition = "完成劇情戰鬥",
		story = "1060000",
		id = 10018,
		icon = "mikasa",
		is_open = 0
	},
	all = {
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		12,
		13,
		14,
		15,
		16,
		17,
		18,
		19,
		20,
		21,
		22,
		23,
		24,
		25,
		26,
		27,
		28,
		29,
		30,
		31,
		32,
		33,
		34,
		62,
		63,
		64,
		65,
		66,
		67,
		68,
		69,
		70,
		71,
		72,
		73,
		74,
		75,
		76,
		77,
		78,
		79,
		80,
		81,
		114,
		115,
		116,
		117,
		118,
		119,
		120,
		121,
		122,
		123,
		124,
		125,
		126,
		127,
		128,
		129,
		130,
		131,
		142,
		143,
		144,
		145,
		146,
		147,
		148,
		163,
		164,
		165,
		166,
		167,
		168,
		169,
		170,
		214,
		215,
		216,
		217,
		218,
		219,
		220,
		246,
		247,
		248,
		249,
		250,
		251,
		252,
		407,
		408,
		409,
		410,
		411,
		412,
		413,
		414,
		415,
		416,
		417,
		494,
		495,
		496,
		497,
		498,
		499,
		500,
		501,
		502,
		503,
		504,
		505,
		506,
		507,
		10011,
		10012,
		10013,
		10014,
		10015,
		10016,
		10017,
		10018
	}
}

return
