PLATFORM_WINDOWSEDITOR = 7
PLATFORM_IPHONEPLAYER = 8
PLATFORM_ANDROID = 11
MAIN_THEME = "main"
CV_LANGUAGE_KEY = "CV_LANGUAGE_"
BILI_SERVER_ID = "388"
SHAREJOY_SERVER_ID = "475"
UNION_SERVER_ID = "439"
SERVER_DAYLIGHT_SAVEING_TIME = false
CONNECT_TIMEOUT = 20
SEND_TIMEOUT = 6
HEART_BEAT_TIMEOUT = 60
AUDIT_SERVER_ID = "2001"
LOGIN_BG_RES_ID = "login"
HOME_PAGE = "http://weibo.com/azurlane"
DOMAIN_LOGIN_1 = "line1.test.cp.login.blhx.biligame.net"
DOMAIN_LOGIN_2 = "line2.test.cp.login.blhx.biligame.net"
DOMAIN_LOGIN_3 = "line3.test.cp.login.blhx.biligame.net"
DOMAIN_LOGIN_4 = "line4.test.cp.login.blhx.biligame.net"
DOMAIN_GS_1 = "line1.test.cp.blhx.biligame.net"
DOMAIN_STATIC_1 = "line1.patch.blhx.biligame.net"
DEFAULT_PORT = 80
LOG = true
LOG_ATLAS = false
LOG_TICK = false
LOG_FMOD = false
LOG_STORY = false
LOG_GUIDE2 = false
LOG_CONNECTION = false
BATTLE_AUTO_ENABLED = 1000001
GAME_RESTOREVIEW_ALREADY = 1000002
ALLOW_FIREND_VISIT_BACKYARD_FLAG = 1000003
SHOW_FIREND_BACKYARD_SHIP_FLAG = 1000004
SHOW_MY_BACKYARD_SHIP_FLAG = 1000005
PROLOGUE_DUNGEON = 100000
EPILOGUE_STORY = "S008"
CURTAIN_STORY = "S999"
BG_RANDOM_RANGE = 12
GUIDE_PROLOGUE_INDEX = 1
ENABLE_GUIDE = true
ENABLE_TEST_OSS = false
SOUND_BACK = "event:/ui/cancel"
SFX_MAIN = "event:/ui/main"
SFX_PANEL = "event:/ui/panel"
SFX_CONFIRM = "event:/ui/confirm"
SFX_CANCEL = "event:/ui/cancel"
SFX_BOAT_CLICK = "event:/ui/boat_click"
SFX_BOAT_DRAG = "event:/ui/boat_drag"
SFX_FURNITRUE_SAVE = "event:/ui/furnitrue_save"
SFX_BOAT_LEVEL_UP = "event:/ui/level_up"
SFX_BREAK_OUT_FULL = "event:/ui/break_out_full"
SFX_AUTO_BATTLE = "event:/ui/auto_battle"
SFX_STEP_MONOPOLY = "event:/ui/step"
SFX_STEP_PILE_COUNTDOWN = "event:/ui/ddldaoshu2"
SFX_STEP_PILE_SUCCESS = "event:/ui/ddlpengzhuang"
PIXEL_PER_UNIT = 100
ITEM_ID_CUBE = 20001
ITEM_ID_SILVER_HOOK = 15001
ITEM_ID_GOLD_HOOK = 15002
ITEM_ID_EQUIP_QUICK_FINISH = 15003
ITEM_ID_ENERGY_QUICK_FINISH = 15004
ITEM_BACKYARD_AREA_EXTEND = 15005
ITEM_ID_FOR_PROPOSE = 15006
BACKYARD_AREA_EXTEND_ITEM_SHOPID = 50001
QUICK_ENERGY_ITEM_SHOPID = 50003
ITEN_EQUIPMENT_FRAGMENT_TYPE = 9
ITEM_ID_FUDAIS = {
	40012,
	40013,
	40014,
	40901,
	40902,
	40903,
	40904,
	40905,
	40906,
	40907,
	40908,
	40909,
	40910
}
ITEM_ID_MULTI_NORMAL = {
	70051
}
QRJ_ITEM_ID_RANGE = {
	41001,
	42000
}
ITEM_ID_REACT_CHAPTER_TICKET = 59823
SHIP_HOOK_TYPE_SILVE = 0
SHIP_HOOK_TYPE_GOLD = 1
DAILY_MAX_COUNT = 3
DROP_TYPE_RESOURCE = 1
DROP_TYPE_ITEM = 2
DROP_TYPE_EQUIP = 3
DROP_TYPE_SHIP = 4
DROP_TYPE_FURNITURE = 5
DROP_TYPE_STRATEGY = 6
DROP_TYPE_SKIN = 7
DROP_TYPE_VITEM = 8
DROP_TYPE_EQUIPMENT_SKIN = 9
DROP_TYPE_NPC_SHIP = 10
DROP_TYPE_WORLD_ITEM = 12
DROP_TYPE_SIREN_EQUIP = 13
DROP_TYPE_ICON_FRAME = 14
DROP_TYPE_CHAT_FRAME = 15
DROP_TYPE_EMOJI = 17
BACKYARD_BUFF = "dorm_exp"
BACKYARD_SHIPINFO_ADDEXP = 1
BACKYARD_SHIPINFO_ADDENERGY = 2
BACKYARD_RECOVERENERGY = 2
BACKYARD_ADDEXP = 5
FLOOR_MAT_TYPE = 5
WALL_PAPER_TYPE = 1
FLOOR_PAPER_TYPE = 4
ADDITION_TYPE_MONEY = 1
ADDITION_TYPE_INTIMACY = 2
ADDITION_TYPE_EXP = 3
BACKYARD_WALL_DIR_LEFT = 1
BACKYARD_WALL_DIR_RIGHT = 2
BACKYARD_RED = Color.New(1, 0.294, 0.08)
BACKYARD_GREEN = Color.New(0.48, 1, 0.03)
BACKYARD_BLUE = Color.New(0.3, 0.63, 0.95)
SHOP_STREET_UPGRADE_SHOPID = 9
BUY_TYPE_RES = 1
BUY_TYPE_ITEM = 2
BUY_TYPE_EQUIPMENT = 3
SHIP_MOD_PREVIEW = 1
SHIP_MOD_UPGRADE = 2
CHAT_POP_STR_LEN = 69
CHAT_POP_STR_LEN_MIDDLE = 54
CHAT_POP_STR_LEN_SHORT = 39
TASK_SUB_TYPE_GIVE_ITEM = 1000
TASK_SUB_TYPE_PT = 1001
TASK_SUB_TYPE_PLAYER_RES = 1002
TASK_SUB_TYPE_GIVE_VIRTUAL_ITEM = 1003
TASK_SUB_TYPE_BOSS_PT = 1004
TASK_SUB_STROY = 1005
TASK_SUB_TYPE_BATTLE_EXP = 1041
TASK_SUB_TYPE_TECHNOLOGY_POINT = 1050
TASK_SUB_TYPE_COLLECT_SHIP = 35
TASK_SUB_TYPE_COLLECT_FURNITURE = 63
SYSTEM_SCENARIO = 1
SYSTEM_ROUTINE = 2
SYSTEM_DUEL = 3
SYSTEM_SHAM = 4
SYSTEM_GUILD = 5
SYSTEM_CHALLENGE = 6
SYSTEM_PERFORM = 7
SYSTEM_ACT_BOSS = 8
SYSTEM_HP_SHARE_ACT_BOSS = 9
SYSTEM_TEST = 10
SYSTEM_SUB_ROUTINE = 11
SYSTEM_WORLD_BOSS = 50
SYSTEM_WORLD = 51
SYSTEM_PROLOGUE = 0
SYSTEM_DODGEM = 98
SYSTEM_SIMULATION = 97
SYSTEM_SUBMARINE_RUN = 96
SYSTEM_DEBUG = 99
SYSTEM_BOSS_EXPERIMENT = 95
CHALLENGE_ACTIVITY_ID = 99999
AUTO_ENABLE_CHAPTER = 103
COLOR_RED = "#FF5C5CFF"
COLOR_YELLOW = "#FFDE38FF"
COLOR_GREEN = "#92FC63FF"
COLOR_BLUE = "#3DC6FFFF"
COLOR_PURPLE = "#D797FFFF"
COLOR_WHITE = "#FFFFFFFF"
COLOR_GREY = "#A2A2A2FF"
COLOR_LIGHT_BLUE = "#C5CFDFFF"
SLIP_TYPE_HRZ = 1
SLIP_TYPE_VERT = 2
REFRESH_BILLBOARD_TIME = 0
PLATFORM_BILIBILI = "bilibili"
PLATFORM_TXWY = "txwykr"
PLATFORM_AIRIJP = "yostarjp"
PLATFORM_AIRIUS = "yostarus"
MAX_FRIEND_COUNT = 50
MAX_BLACKLIST_COUNT = 50
MAX_BUILD_WORK_COUNT = 10
MAX_REPLACE_RIVAL_COUNT = 5
AABBUDUD = "dettimrepsignihtyrevednaeurtsignihton"
LOAD_TYPE_SCENE = "_load_type_scene"
LOAD_TYPE_LAYER = "_load_type_layer"
AUTO_BATTLE_LABEL = "autoBattle"
RARE_SHIP_VIBRATE = "rare_ship_vibrate"
DISPLAY_SHIP_GET_EFFECT = "display_ship_get_effect"
SHOW_TOUCH_EFFECT = "show_touch_effect"
BG_FIT_MODE = "bgFitMode"
ALLOW_FIREND_VISIT_BACKYARD = "allow_friend_visit_backyard"
SHOW_FIREND_BACKYARD_SHIP = "show_friend_backyard_ship"
SHOW_MY_BACKYARD_SHIP = "show_my_backyard_ship"
DISCONNECT_TIME_OUT = "time_out"
LOCK_PROPOSE = false
LOCK_CLASSROOM = false
LOCK_SHAM_CHAPTER = false
LOCK_PT_VALUE = false
LOCK_EQUIP_SKIN = false
LOCK_MITIGATION = false
LOCK_SEC_FLOOR = false
LOCK_FULL_EXP = false
LOCK_CLICK_MINGSHI = false
LOCK_DOWNVOTE = true
LOCK_TECHNOLOGY = false
LOCK_SECONDARY = false
LOCK_HIDE_CHAT = false
LOCK_SUBMARINE = false
LOCK_SOS = false
LOCK_ILLUSTRATOR = false
LOCK_SKIN_SORT = false
LOCK_COMMANDER = false
LOCK_CLEAR_ACCOUNT = true
LOCK_COMMANDER_TALENT_TIP = false
LOCK_GUILD_SHOP = true
LOCK_DESTROY_GUIDE = true
LOCK_BACKYARD_TEMPLATE = true
LOCK_TOWERCLIMBING_AWARD = false
DEFAULT_CVVOLUME = 0.8
DEFAULT_BGMVOLUME = 0.8
DEFAULT_SEVOLUME = 0.8
HIDE_CHAT_FLAG = "HideChat"
ERROR_MESSAGE = {
	"无效操作",
	"缺少配置",
	"超时",
	"时间未到",
	"已达到最大等级",
	"已达到最大数量限制",
	"已经完成",
	"未定义参数",
	"错误参数",
	"栏位已满",
	"数据库错误",
	"系统异常",
	"禁止登录",
	nil,
	"注册数已达上限，感谢您的支持。",
	nil,
	nil,
	nil,
	"无效的重复操作",
	"数据不存在",
	"玩家不存在",
	"舰娘不存在",
	"物品不存在",
	"装备不存在",
	"任务不存在",
	"战斗信息不存在",
	"采集点不存在",
	"好友不存在",
	"邮件不存在",
	"目标不足",
	"资源不足",
	"金币不足",
	"石油不足",
	"银沙不足",
	"晶钻不足",
	"家具币不足",
	"物品不足",
	"食物不足",
	"体力不足",
	"不合法限制条件",
	"等级不符合",
	"类型不符合",
	[2015.0] = "名字已被使用",
	[2011.0] = "名字过长",
	[1010.0] = "账号错误",
	[2014.0] = "名字错误字符",
	[2013.0] = "名字有屏蔽词",
	[2010.0] = "名字检查错误",
	[1011.0] = "账号已存在",
	[1040.0] = "服务器已关闭",
	[1030.0] = "md5验证错误",
	[2012.0] = "名字过短",
	[1031.0] = "md5长度错误",
	[4020.0] = "舰娘是看板娘",
	[4030.0] = "舰娘在编队中",
	[4201.0] = "礼包码已过期",
	[4010.0] = "舰娘不可用",
	[4203.0] = "礼包码不存在",
	[9999.0] = "未定义错误",
	[4205.0] = "礼包码兑换有误，请重试",
	[4206.0] = "该类型礼包已被兑换",
	[3010.0] = "舰娘不可战斗",
	[3020.0] = "前置关卡未通过",
	[4207.0] = "没有礼包兑换URL",
	[4204.0] = "礼包码已被使用",
	[4050.0] = "相同的舰娘",
	[4040.0] = "舰娘不在编队中",
	[1020.0] = "密码错误",
	[4202.0] = "该渠道不支持",
	[1012.0] = "纯数字账号"
}
SPECIAL_DATE = {
	{
		"20200401",
		"login",
		"loginbg_0401",
		"login_0401"
	}
}
SPECIAL_PROPOSE = {}
CRI_BG_FLAG = false
OPEN_ESCORT = false
OPEN_REMASTER = true
OPEN_AIR_DOMINANCE = true
AUTO_LINKLINK = false
PLAY_OPENING = true
OP_VERSION = "20200521"
OPEN_TEC_TREE_SYSTEM = true
SECRETARY_POS = false
ADAPT_MIN = 1.8
ADAPT_TARGET = 2
ADAPT_NOTICE = 1.8
LOCK_FRAGMENT_SHOP = false
